### Sebastián Rodríguez
### 20003076

                                        # XOR - Compuertas y perceptrones

In [3]:
import numpy as np

In [4]:
def Activacion(z):
    return (z >= 0).astype(np.float)
Activacion(np.array([1]))

array([1.])

In [5]:
def Transf(x, Pesos):
    return np.matmul(x, Pesos)

Transf(np.array([1, 1, 1.]), np.array([1.,1.,-2.]))

def perceptron(x, Pesos):
    x = np.column_stack((x, np.ones(x.shape[0])))
    return Activacion(Transf(x, Pesos)).reshape(-1, 1)

In [8]:
X = np.array([[0., 0.], [0., 1.], [1., 0.], [1., 1.]])
perceptron(X, np.array([1., 1., 0]))

Pesos = np.array([10., 10., -15.])
and_ = perceptron(X, Pesos)


Pesos = np.array([20., 20., -10.])
or_ = perceptron(np.array(X), Pesos)

Y = np.array([0, 1]).reshape(-1, 1)
Pesos = np.array([-1., 0.5])
not_ = perceptron(np.array(Y), Pesos)


In [11]:
Funcion_XOR = lambda a, b : or_fn( and_fn(a, not_fn(b)), and_fn(not_fn(a), b) )

and_fn = lambda a, b : perceptron(np.column_stack((a, b)), np.array([10., 10., -15.]))
or_fn = lambda a, b : perceptron(np.column_stack((a, b)), np.array([20., 20., -10.]))
not_fn = lambda x : perceptron(x, np.array([-1., 0.5]))


In [13]:
print("Entradas:")
print(X)
print("Función lógica XOR: ")
print(Funcion_XOR(X[:, 0], X[:, 1]))

Entradas:
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Función lógica XOR: 
[[0.]
 [1.]
 [1.]
 [0.]]
